spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/buildprice_db
    username: buildprice_user
    password: buildprice_pass

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  sinapi:
    upload-dir: /tmp/sinapi

  batch:
    jdbc:
      platform: postgresql
      initialize-schema: always
    job:
      enabled: false

